apiVersion: v1
kind: Secret
metadata:
  name: skel-npp-secrets-prod
type: Opaque
stringData:
  INFLUX_URI: "http://canopus.u132.net:8086"
  INFLUX_ORG: "df560bffb5acc1c6"
  INFLUX_BUCKET: "npp-bucket"
  INFLUX_TOKEN: "V7pcAci-WbG2igLB_hzOKrSqgyxJcmJuz3AxRPbytReklQLF5S3FRyDNOhQ1qOCItDaYCtEfKLIjKrZfzLf9tA=="
