apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekm
  template:
    metadata:
      labels:
        app: ekm
    spec:
      containers:
      - name: skel-ekm
        image: syspulse/skel-ekm:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
             name: skel-ekm-configmap-prod
        - secretRef:
             name: skel-ekm-secrets-prod
        args: ["--ekm.uri","$(EKM_URI)","--ekm.key","$(EKM_KEY)","--ekm.device","$(EKM_DEVICE)","--influx.uri","$(INFLUX_URI)","--influx.user","$(INFLUX_USER)","--influx.pass","$(INFLUX_PASS)","--influx.db","$(INFLUX_DB)","--log.file","$(LOG_FILE)","influx"]
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
